language: python

python:
  - 3.6

install:
  - pip install pytest==4.1.0 pytest-cov python-coveralls
  - pip install -e .

script:
  - pytest --cov mkdocs-abs-rel-plugin

after_success:
  - coveralls